name: Build
on: [push]
jobs:
  main:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.deps.clj
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-
      - name: Install clj-kondo
        uses: DeLaGuardo/setup-clojure@13.0
        with:
          clj-kondo: 2022.05.31
      - name: Lint
        run: clj-kondo --lint src
